<?php
/**
 * @file
 * menu_link.4d5f707cb94c86548206be7b9f617ac8d44275d6.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/user-interface/menu-block',
  'link_title' => 'Menu block',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Configure menu block.',
    ),
  ),
  'router_path' => 'admin/config/user-interface/menu-block',
  'parent_identifier' => '5440005a9acc41ae6ea0335a022797c71396bfe5',
);

$dependencies = array(
  'menu_link.5440005a9acc41ae6ea0335a022797c71396bfe5' => 'menu_link.5440005a9acc41ae6ea0335a022797c71396bfe5',
);

$optional = array();

$modules = array();
