<?php
/**
 * @file
 * menu_link.7ac2fe9363dc618a5d0c6d31caac2b99b59de616.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'node/7',
  'link_title' => 'App 1 Page 3',
  'menu_name' => 'main-menu',
  'weight' => '-48',
  'expanded' => '0',
  'options' => array(),
  'router_path' => 'node/%',
  'parent_identifier' => 'd7a98e94da99a489cbf922a714f09f4a8134bd1d',
);

$dependencies = array(
  'menu_link.d7a98e94da99a489cbf922a714f09f4a8134bd1d' => 'menu_link.d7a98e94da99a489cbf922a714f09f4a8134bd1d',
);

$optional = array();

$modules = array();
