<?php
/**
 * @file
 * menu_link.1e794dcecda8cadb30f8183ad41173cdb4e274ce.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'node/5',
  'link_title' => 'App 1 - Page 1',
  'menu_name' => 'main-menu',
  'weight' => '-50',
  'expanded' => '0',
  'options' => array(),
  'router_path' => 'node/%',
  'parent_identifier' => 'd7a98e94da99a489cbf922a714f09f4a8134bd1d',
);

$dependencies = array(
  'menu_link.d7a98e94da99a489cbf922a714f09f4a8134bd1d' => 'menu_link.d7a98e94da99a489cbf922a714f09f4a8134bd1d',
);

$optional = array();

$modules = array();
