<?php
/**
 * @file
 * menu_link.fb1cc4c04914f71ae2c5fa8ce09211d09c81baa4.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'node/6',
  'link_title' => 'App 1 - Page 2',
  'menu_name' => 'main-menu',
  'weight' => '-49',
  'expanded' => '0',
  'options' => array(),
  'router_path' => 'node/%',
  'parent_identifier' => 'd7a98e94da99a489cbf922a714f09f4a8134bd1d',
);

$dependencies = array(
  'menu_link.d7a98e94da99a489cbf922a714f09f4a8134bd1d' => 'menu_link.d7a98e94da99a489cbf922a714f09f4a8134bd1d',
);

$optional = array();

$modules = array();
