<?php
/**
 * @file
 * menu_link.82f5fa90f3994e7a269eb901a033e1a8c1562569.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'node/3',
  'link_title' => 'Applications',
  'menu_name' => 'main-menu',
  'weight' => '-49',
  'expanded' => '0',
  'options' => array(),
  'router_path' => 'node/%',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.main_menu' => 'menu.main_menu',
);

$optional = array();

$modules = array();
