<?php
/**
 * @file
 * menu_link.c5ad0d6838c33530812357e12a76441ddbc2c8e9.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config/system/backup_migrate',
  'link_title' => 'Backup and Migrate',
  'menu_name' => 'management',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => 'Backup/restore your database and files or migrate data to or from another Drupal site.',
    ),
  ),
  'router_path' => 'admin/config/system/backup_migrate',
  'parent_identifier' => '4e354a16bb1634106a3ada7d78189d4d30588ae6',
);

$dependencies = array(
  'menu_link.4e354a16bb1634106a3ada7d78189d4d30588ae6' => 'menu_link.4e354a16bb1634106a3ada7d78189d4d30588ae6',
);

$optional = array();

$modules = array();
