<?php
/**
 * @file
 * menu_link.d7a98e94da99a489cbf922a714f09f4a8134bd1d.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'node/4',
  'link_title' => 'Application 1',
  'menu_name' => 'main-menu',
  'weight' => '-50',
  'expanded' => '0',
  'options' => array(),
  'router_path' => 'node/%',
  'parent_identifier' => '82f5fa90f3994e7a269eb901a033e1a8c1562569',
);

$dependencies = array(
  'menu_link.82f5fa90f3994e7a269eb901a033e1a8c1562569' => 'menu_link.82f5fa90f3994e7a269eb901a033e1a8c1562569',
);

$optional = array();

$modules = array();
