<?php
/**
 * @file
 * menu_link.b6dd8193070ba1358d3ab5357820f2e466bbc8c8.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'node/1',
  'link_title' => 'Credentials',
  'menu_name' => 'navigation',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => '',
    ),
  ),
  'router_path' => 'node/%',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.navigation' => 'menu.navigation',
);

$optional = array();

$modules = array();
